API documentation PoC
UKGovernmentBEIS/energy-label-service pull request #105
Opened 2022-02-14 18:12 UTC by dannybetts

Created a PoC for the API documentation screens and approach. The screens / controller need sorting out to use the correct macros / layout and sort the code structure. Would be interested in your opinions on the basic approach.

2022-02-15 10:07 UTC, dannybetts commented on src/main/resources/templates/apidocumentation/apiDocumentationForTag.ftl
> +    <@govukDetails.details summaryTitle="${operation.getSummary()}">
You have to use the java method signatures as there are `summary()` and 'description()' methods in the Operation class

2022-02-21 16:54 UTC, jamesbarnett91 requested changes

2022-02-21 16:54 UTC, jamesbarnett91 commented on src/main/java/uk/gov/beis/els/api/common/ApiDocumentationController.java
> +  private OpenAPI getOpenApiResponse(HttpServletRequest request) {
We should make this request once on app start and cache the OpenAPI object. Can just create an `OpenApiService` and store as a member variable, and populate it on start with `@EventListener(ApplicationReadyEvent::class)`. That way we don't request and re-parse the object every request.

2022-02-21 16:54 UTC, jamesbarnett91 commented on src/main/java/uk/gov/beis/els/api/common/ApiDocumentationController.java
> +   return restTemplate.getForEntity(baseUrl + "/v3/api-docs/", OpenAPI.class).getBody();
We should always just be able to hit `http://localhost:8080/v3/api-docs` here, as we're calling to ourselves. That also saves us going all the way back out to the internet and back in to our app, and we don't need to bind in the `HttpServletRequest`

2022-02-21 16:54 UTC, jamesbarnett91 commented on src/test/java/uk/gov/beis/els/ControllerSmokeTest.java
> +    ignoredEndpoints = Arrays.asList(
Nit: worth renaming this to `ignoredEndpointPrefixes` just to make it clear this will match anything that starts with these strings.

2022-02-21 18:26 UTC, jamesbarnett91 approved these changes

2022-02-22 11:53 UTC, merged