Feature/elg42/implement package calculator for water heaters
UKGovernmentBEIS/energy-label-service pull request #115
Opened 2022-02-25 16:15 UTC by FernandoRamirez-De-Aguilar

2022-02-28 12:15 UTC, matteason requested changes
Couple of design changes on the form page but the calculations themselves look good, thanks very much @FernandoRamirez-De-Aguilar

2022-02-28 13:50 UTC, FernandoRamirez-De-Aguilar commented on src/main/java/uk/gov/beis/els/categories/waterheaters/model/WaterSolarPackagesCalculatorForm.java
> +  @FieldPrompt("Can a solar collector be included in this package?")
done

2022-02-28 13:51 UTC, FernandoRamirez-De-Aguilar commented on src/main/java/uk/gov/beis/els/categories/waterheaters/model/WaterSolarPackagesCalculatorForm.java
> +  @FieldPrompt("Water heating efficiency (%)")
done

2022-02-28 13:52 UTC, FernandoRamirez-De-Aguilar commented on src/main/java/uk/gov/beis/els/categories/waterheaters/model/WaterSolarPackagesCalculatorForm.java
> +  @FieldPrompt("Can a hot water storage tank be included in this package?")
done

2022-02-28 13:52 UTC, FernandoRamirez-De-Aguilar commented on src/main/resources/templates/categories/water-heaters/waterSolarPackagesCalculator.ftl
> +    <@govukTextInput.textInput path="form.annualNonSolarHeatContribution"/>
done

2022-02-28 13:52 UTC, FernandoRamirez-De-Aguilar commented on src/main/resources/templates/categories/water-heaters/waterSolarPackagesCalculator.ftl
> +    <@govukTextInput.textInput path="form.waterHeatingEfficiencyPercentage"/>
done

2022-02-28 13:53 UTC, FernandoRamirez-De-Aguilar commented on src/main/resources/templates/categories/water-heaters/waterSolarPackagesCalculator.ftl
> +<#--<@defaultPage pageTitle="Do you need help calculating the energy rating for this package?">-->
how awkward

2022-02-28 13:53 UTC, FernandoRamirez-De-Aguilar commented on src/main/resources/templates/categories/water-heaters/waterSolarPackagesCalculator.ftl
> +<#--<@defaultPage pageTitle="Do you need help calculating the energy rating for this package?">-->
done

2022-02-28 14:36 UTC, matteason approved these changes

2022-03-01 10:33 UTC, jamesbarnett91 approved these changes

2022-03-01 10:33 UTC, merged