Process schema property examples
UKGovernmentBEIS/energy-label-service pull request #116
Opened 2022-02-28 11:36 UTC by dannybetts

2022-02-28 11:42 UTC, dannybetts commented on src/main/java/uk/gov/beis/els/api/openapi/OpenApiPropertyCustomiser.java
> +              if (schema.getDescription().contains("pixels")) {
@jamesbarnett91 I did think about creating a specific annotation for pixel fields and QR code fields (processed below) and using that to determine the example property, but that might be overkill. For now it's based on the description. Thoughts? Could also base it on field name? Either could be inconsistent.

2022-02-28 11:54 UTC, dannybetts commented on src/main/java/uk/gov/beis/els/api/openapi/OpenApiPropertyCustomiser.java
> +        schema.setExample("100"); // set pixels to something the user can actually see (i.e. bigger than 1 pixel)
@jamesbarnett91 I did think about creating a specific annotation for pixel fields and QR code fields (processed below) and using that to determine the example property, but that might be overkill. For now it's based on the description. Thoughts? Could also base it on field name? Either could be inconsistent.

2022-02-28 16:18 UTC, jamesbarnett91 requested changes

2022-03-01 10:44 UTC, dannybetts commented on src/main/java/uk/gov/beis/els/api/openapi/OpenApiPropertyCustomiser.java
> +        schema.setExample("100"); // set pixels to something the user can actually see (i.e. bigger than 1 pixel)
Done

2022-03-01 10:46 UTC, merged