Feature/ELG-46/implement package calculator for combination heaters
UKGovernmentBEIS/energy-label-service pull request #136
Opened 2022-03-21 15:34 UTC by FernandoRamirez-De-Aguilar

Energy label calculator for space combination heaters in 2 flavours: Boilers & heat pumps
 
This is how the heat pump version looks, boiler is similar but with corresponding fields:
![localhost_8080_categories_space-heaters_package-combination-heater_heat-pump_calculator](https://user-images.githubusercontent.com/98316465/159295418-8de9f1fe-35f1-46d0-999a-ee8fa7f02e2c.png)

2022-03-21 15:46 UTC, FernandoRamirez-De-Aguilar commented on src/main/java/uk/gov/beis/els/categories/spaceheaters/model/BoilerCombinationCalculatorForm.java
> +  @Schema(type = "integer")
I left the schema values from the water heaters form just to make it quicker to make the new API endpoints

2022-03-22 15:43 UTC, matteason requested changes

2022-03-22 15:43 UTC, matteason commented on src/main/resources/templates/categories/space-heaters/boilerCombinationCalculator.ftl
> +    <@govukFieldset.fieldset legendHeading="Solar Collector" legendSize="h2">
Lower case c, `Solar collector`

2022-03-22 15:43 UTC, matteason commented on src/main/resources/templates/categories/space-heaters/heatPumpCombinationCalculator.ftl
> +    <@govukFieldset.fieldset legendHeading="Solar Collector" legendSize="h2">
Lower case c, `Solar collector`

2022-03-22 15:43 UTC, matteason commented on src/main/resources/templates/categories/space-heaters/spaceHeaterPackagesCalculatorCommon.ftl
> +    <@govukFieldset.fieldset legendHeading="Solar Collector" legendSize="h2">
Lower case c, `Solar collector`

2022-03-22 17:25 UTC, matteason approved these changes

2022-03-23 10:36 UTC, merged