Feature/ELG-10/APIs for Refrigerating appliances
UKGovernmentBEIS/energy-label-service pull request #93
Opened 2022-02-08 11:55 UTC by FernandoRamirez-De-Aguilar

API endpoints for

- Household fridges and freezers
- Wine storage appliances

2022-02-09 16:14 UTC, dannybetts commented on src/main/java/uk/gov/beis/els/categories/refrigeratingappliances/model/FridgesFreezersForm.java
>    @Digits(groups = FridgeGroup.class, integer = 3, fraction = 0, message = "Enter the total volume of chill and unfrozen compartments in litres up to 3 digits long")
Missing some NotNull constraints

2022-02-09 16:15 UTC, dannybetts requested changes
Update NotBlank constraints to be NotNull and add missing ones

2022-02-10 09:26 UTC, FernandoRamirez-De-Aguilar commented on src/main/java/uk/gov/beis/els/categories/refrigeratingappliances/model/FridgesFreezersForm.java
>    @Digits(groups = FridgeGroup.class, integer = 3, fraction = 0, message = "Enter the total volume of chill and unfrozen compartments in litres up to 3 digits long")
done

2022-02-10 10:08 UTC, jamesbarnett91 approved these changes
LGTM, thanks

2022-02-10 15:50 UTC, merged