ELG-22 APIs for Washing Machines
UKGovernmentBEIS/energy-label-service pull request #99
Opened 2022-02-11 15:38 UTC by FernandoRamirez-De-Aguilar

API endpoints for washing machines

New `ApiValuesFromRatingClassRange` annotation for using a custom rating range instead of the ones defined by the current legislation.

2022-02-11 16:19 UTC, dannybetts requested changes
Change washer dryer description

2022-02-14 10:04 UTC, FernandoRamirez-De-Aguilar commented on src/main/java/uk/gov/beis/els/api/categories/washingmachines/WashingMachinesApiController.java
> +      description = "You must attach the label to the front or top of the product so that it’s easy to see. If it's a built-in washing machine it doesn't have to be attached to the product, but it mu
done

2022-02-14 11:01 UTC, dannybetts approved these changes

2022-02-14 12:16 UTC, jamesbarnett91 approved these changes
Thanks LGTM

2022-02-14 12:16 UTC, merged